"""Sample supplier proposals for the Proposal Comparison Engine demo."""

SAMPLE_PROPOSALS = {
    "scenario_name": "Corporate Events Management Services — 2-Year Engagement",
    "scenario_description": (
        "Airbnb is sourcing a partner for a 2-year engagement to plan and execute "
        "corporate events. Annual spend is approximately $2M. Scope includes 4 major "
        "company events per year (all-hands, leadership offsite, summer celebration, "
        "holiday event) plus 8–12 smaller team events. The selected partner must handle "
        "venue sourcing, catering, A/V production, travel logistics, and post-event "
        "reporting. Proposals were solicited from two vendors with contrasting profiles."
    ),
    "proposals": [
        {
            "supplier_name": "Eventide Solutions",
            "proposal_text": (
                "PROPOSAL FOR CORPORATE EVENTS MANAGEMENT SERVICES\n"
                "Submitted to: Airbnb, Inc.\n"
                "Submitted by: Eventide Solutions\n"
                "Date: January 15, 2026\n"
                "RFP Reference: AIR-PROC-2026-0042\n\n"

                "1. COMPANY OVERVIEW\n\n"
                "Eventide Solutions is a premier full-service corporate events management "
                "agency founded in 2011. With over 200 employees across offices in San Francisco, "
                "New York, Chicago, Austin, and Miami, we are one of the largest independently "
                "owned event management firms in the United States. Over the past 15 years, "
                "Eventide has planned and executed more than 3,500 corporate events for Fortune "
                "500 clients, including technology, financial services, and consumer goods companies.\n\n"
                "We are ISO 27001 certified, ensuring that all client data and event logistics "
                "are handled with enterprise-grade security protocols. Eventide is also a certified "
                "Women's Business Enterprise (WBE) through the Women's Business Enterprise National "
                "Council (WBENC). We carry $5M in general liability insurance and maintain "
                "comprehensive errors and omissions coverage.\n\n"
                "Our approach is built on operational excellence, leveraging proven methodologies "
                "and synergistic partnerships to deliver transformative event experiences that "
                "drive stakeholder alignment and organizational momentum.\n\n"

                "2. UNDERSTANDING OF REQUIREMENTS\n\n"
                "Airbnb seeks a strategic events partner to plan and execute a portfolio of "
                "corporate events over a 2-year engagement period. We understand the scope to include:\n"
                "- 4 major company events per year: All-Hands Meeting, Leadership Offsite, "
                "Summer Celebration, and Holiday Event\n"
                "- 8–12 smaller team-level events per year\n"
                "- Full-service management: venue sourcing, catering, A/V production, travel "
                "logistics, and post-event reporting\n"
                "- Alignment with Airbnb's brand values of belonging, creativity, and community\n\n"
                "We recognize that each event type requires a differentiated approach while "
                "maintaining a consistent brand experience across the portfolio.\n\n"

                "3. PROPOSED APPROACH\n\n"
                "Eventide will deploy our Enterprise Events Framework (EEF), a proprietary "
                "methodology that integrates strategic planning, creative design, logistics "
                "management, and post-event analytics into a unified delivery model.\n\n"
                "Venue Sourcing: We maintain an exclusive network of 2,000+ vetted venues "
                "nationwide. Our venue procurement team will present curated shortlists within "
                "10 business days of brief receipt, including virtual site tours and detailed "
                "comparison matrices.\n\n"
                "Catering & Hospitality: Our culinary partnerships span 150+ preferred caterers. "
                "All menus will accommodate dietary restrictions, cultural preferences, and "
                "sustainability requirements.\n\n"
                "A/V & Production: Full in-house production capability including stage design, "
                "lighting, sound, live streaming, and hybrid event technology.\n\n"
                "Travel Logistics: Integrated travel management for attendee transportation, "
                "accommodation blocks, and ground logistics.\n\n"
                "Post-Event Reporting: Comprehensive event reports delivered within 5 business "
                "days, including attendee satisfaction surveys, budget reconciliation, and "
                "strategic recommendations for future events.\n\n"
                "We will leverage our proprietary innovation engine to identify cutting-edge "
                "solutions that drive paradigm shifts in the corporate events space, ensuring "
                "Airbnb remains at the forefront of experiential excellence.\n\n"

                "4. TEAM & STAFFING\n\n"
                "Eventide will assign a dedicated team to the Airbnb account:\n"
                "- 2 Senior Account Managers (each with 10+ years of experience)\n"
                "- 1 Creative Director\n"
                "- 1 Production Manager\n"
                "- 2 Event Coordinators\n"
                "- Access to our full bench of 200+ specialists as needed\n\n"
                "The account team will be based in our San Francisco office for proximity to "
                "Airbnb headquarters. Quarterly business reviews (QBRs) will be conducted with "
                "Airbnb's procurement and events leadership teams.\n\n"

                "5. PRICING\n\n"
                "Eventide proposes a fixed annual fee of $2,400,000 for the full scope of services "
                "described above. This fee structure provides budget certainty and eliminates "
                "per-event cost variability.\n\n"
                "Included in the annual fee:\n"
                "- All staff time for planning, execution, and post-event reporting\n"
                "- Project management tools and technology platform access\n"
                "- Quarterly business reviews and monthly status reports\n"
                "- Up to 4 major events and 10 smaller events per year\n\n"
                "Not included (passed through at cost plus 12% management fee):\n"
                "- Venue rental fees\n"
                "- Catering and food & beverage costs\n"
                "- A/V equipment rental (beyond our in-house inventory)\n"
                "- Travel and accommodation for attendees\n"
                "- Printed materials and signage\n\n"
                "Change orders for work outside the defined scope will be billed at $150/hour "
                "and require a formal change order request with 5 business day turnaround for "
                "approval. Annual price escalation is tied to the Consumer Price Index (CPI), "
                "capped at 3% per year.\n\n"
                "Payment terms: Net 45 from invoice date.\n\n"

                "6. TERMS & CONDITIONS\n\n"
                "Contract Duration: 2 years with option to renew for successive 1-year terms.\n"
                "Termination: Either party may terminate with 90 days written notice, subject to "
                "a 30-day cure period for any curable breach.\n"
                "Service Level Agreements:\n"
                "- Response time: 48 hours for standard requests, 4 hours for urgent matters\n"
                "- On-time delivery: 99% target for all event milestones\n"
                "- Financial penalties: 5% service credit per SLA incident, capped at 15% of "
                "monthly fees\n"
                "- Quarterly performance scorecards aligned to agreed KPIs\n"
                "Intellectual Property: All event concepts and materials created for Airbnb are "
                "work-for-hire and become Airbnb's property.\n"
                "Insurance: $5M general liability, $2M professional liability, $1M cyber liability.\n"
                "Data Protection: Full compliance with CCPA and SOC 2 Type II controls.\n"
                "Carbon Offset Program: Eventide offsets the carbon footprint of all events "
                "through verified carbon credit purchases, included in the annual fee.\n\n"

                "7. REFERENCES\n\n"
                "- Salesforce: Managed their annual Dreamforce partner events program (2019–present). "
                "Contact: Sarah Chen, VP of Global Events.\n"
                "- Cisco: Planned and executed 25+ leadership offsites per year across North America "
                "(2020–2024). Contact: Michael Torres, Director of Corporate Services.\n"
                "- Deloitte: Delivered their West Coast office holiday event series for 3 consecutive "
                "years. Contact: Priya Gupta, Senior Manager, Workplace Experience.\n"
            ),
        },
        {
            "supplier_name": "Mosaic Collective",
            "proposal_text": (
                "MOSAIC COLLECTIVE\n"
                "A Proposal for Airbnb's Corporate Events Partnership\n\n"

                "1. COMPANY OVERVIEW\n\n"
                "Mosaic Collective is a creative-first events agency founded in 2019 with a mission "
                "to transform corporate gatherings into cultural moments. We are a team of 45 "
                "designers, strategists, producers, and technologists headquartered in Brooklyn, NY "
                "with a satellite studio in Los Angeles.\n\n"
                "In seven years, we have built a reputation as the go-to agency for technology "
                "companies that refuse to settle for conventional events. Our work has been featured "
                "in Fast Company, Wired, and Event Marketer. We are proud to hold both MBE "
                "(Minority Business Enterprise) and LGBTBE (LGBT Business Enterprise) certifications.\n\n"
                "We carry $1M in general liability insurance, which we have found sufficient for "
                "our current portfolio of engagements.\n\n"

                "2. UNDERSTANDING OF REQUIREMENTS\n\n"
                "We see Airbnb's events portfolio as an opportunity to create belonging at scale. "
                "Your four major events and 8–12 team events are not just logistical exercises — "
                "they are expressions of Airbnb's culture and values. Each should feel intentional, "
                "human, and unforgettable.\n\n"
                "We understand you need a partner who can handle the full production lifecycle: "
                "venue sourcing, catering, A/V, travel, and reporting. But more importantly, you "
                "need a creative partner who can elevate each event from a meeting into an experience.\n\n"

                "3. PROPOSED APPROACH\n\n"
                "Creative Direction: Every event begins with a story. Our creative directors develop "
                "a narrative arc for each event that ties back to Airbnb's mission and current "
                "company priorities. We don't do cookie-cutter events.\n\n"
                "Immersive Experiences: We specialize in AR-integrated activations, custom event "
                "apps with real-time engagement features (live polls, networking matchmaking, "
                "content sharing), and spatial design that transforms venues into branded worlds. "
                "For Airbnb's Summer Celebration, imagine an AR scavenger hunt through a curated "
                "neighborhood that brings the 'belong anywhere' concept to life.\n\n"
                "Venue Sourcing: We work with unconventional venues — art galleries, rooftop farms, "
                "historic theaters, cultural spaces — that reflect Airbnb's brand personality. We "
                "also source traditional conference spaces when the event calls for it.\n\n"
                "Catering: We partner with local, chef-driven caterers who create menus inspired by "
                "the event theme and local food culture. All menus include dietary accommodation.\n\n"
                "A/V & Production: We work with a trusted network of production partners and bring "
                "our own creative technologists to integrate digital experiences into the physical "
                "event space.\n\n"
                "Post-Event Insights: We deliver post-event decks within 7 business days that go "
                "beyond satisfaction surveys to include engagement analytics, social media impact, "
                "and creative performance metrics.\n\n"

                "4. TEAM & STAFFING\n\n"
                "Your Mosaic team:\n"
                "- Jordan Martinez, Creative Director: Jordan is the creative visionary behind some "
                "of our most celebrated events. Jordan led Stripe's 2024 Global Summit, which was "
                "named 'Corporate Event of the Year' by Event Marketer. Jordan also managed Figma's "
                "Annual User Conference, transforming it from a 500-person gathering into a 3,000-person "
                "cultural event. Jordan is the heart of this engagement and will be personally involved "
                "in every major event.\n"
                "- 2 Senior Event Coordinators\n"
                "- Production support drawn from our 45-person team as needed\n\n"
                "Jordan's involvement is what makes this partnership special. Their creative intuition "
                "and deep understanding of tech culture is unmatched in our industry.\n\n"

                "5. PRICING\n\n"
                "Mosaic proposes a Time & Materials model with monthly fee caps to provide cost "
                "control while maintaining the flexibility to scale creative investment up or down "
                "based on event complexity.\n\n"
                "Annual budget: $1,800,000 (estimated)\n"
                "- Creative Director: $250/hour\n"
                "- Senior Coordinator: $175/hour\n"
                "- Production Staff: $125/hour\n"
                "- Monthly cap: $150,000\n\n"
                "Pass-through costs (venue, catering, A/V rental, travel) are billed at cost with "
                "no markup.\n\n"
                "Payment terms: Net 30 from invoice date.\n\n"
                "We do not include a price escalation clause. Our rates are reviewed annually and "
                "adjusted based on market conditions, which we discuss transparently with our clients.\n\n"

                "6. TERMS & CONDITIONS\n\n"
                "Contract Duration: 2 years.\n"
                "Termination: Either party may terminate with 30 days written notice. No cure period "
                "— we believe that if a partnership isn't working, both parties should be free to "
                "move on quickly.\n\n"
                "Service Commitments: Rather than a traditional SLA document, Mosaic operates under "
                "a Service Commitment Framework:\n"
                "- We will respond to requests typically within 24 hours during business days\n"
                "- We will use best efforts to meet all agreed timelines\n"
                "- We will provide regular updates through our preferred communication channels\n"
                "- If issues arise, we will work collaboratively with Airbnb to resolve them "
                "expeditiously\n"
                "We find that rigid SLA structures can create adversarial dynamics. Our approach "
                "prioritizes partnership and open communication over contractual penalties.\n\n"
                "Intellectual Property: All event concepts are co-owned. Mosaic retains the right "
                "to showcase work in our portfolio (with Airbnb's approval on specific assets).\n"
                "Insurance: $1M general liability.\n"
                "Data Protection: We comply with applicable data protection regulations.\n\n"

                "7. REFERENCES\n\n"
                "- Stripe: Led Stripe's 2024 Global Summit across 3 cities (San Francisco, London, "
                "Singapore) with 5,000+ total attendees. Contact: Aisha Patel, Head of Events.\n"
                "- Figma: Managed Figma's Annual User Conference for 2 consecutive years, growing "
                "attendance from 500 to 3,000. Contact: Raj Krishnamurthy, VP of Community.\n"
                "- Notion: Designed and produced Notion's first-ever company retreat for 800 "
                "employees across 15 countries. Contact: Elena Vasquez, Chief of Staff.\n"
            ),
        },
    ],
}
